name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("testthat", "dplyr", "ggplot2", "sf", "car", "tibble", "quanteda", "reticulate"))'
      - name: Run tests
        run: |
          Rscript tests/run_all_tests.R
