
name: Run R Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install testthat
      run: |
        R -e 'install.packages("testthat", repos="https://cloud.r-project.org")'

    - name: Run tests
      run: |
        R -e 'testthat::test_dir("tests", reporter = "summary")'
