name: Render Notebooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("quarto", "rmarkdown", "dplyr", "ggplot2", "srvyr", "sf", "naniar", "knitr", "cluster", "factoextra"))'
      - name: Render .qmd
        run: |
          Rscript -e 'quarto::quarto_render("notebooks/Survey_Education_Summary.qmd")'
